url: stevenicolson.github.io/stevenicolson
baseurl: 

# Site settings
title: Steve Nicolson
email: snicolson72@gmail.com
description: "Actor"


# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty